# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='profile',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
