# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150)),
                ('apellido', models.CharField(default='', max_length=150)),
                ('foto', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='perfil_alumno')),
                ('animal', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('sueno', models.CharField(blank=True, max_length=70, null=True)),
                ('juego', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Logo de equipo', null=True, upload_to='equipo_logo', verbose_name='Logo de equipo')),
                ('portada', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Portada de equipo', null=True, upload_to='equipo_portada', verbose_name='Portada de equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('seccion', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bg', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='materia_media')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='materia_media')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tokens', models.IntegerField()),
                ('disponible', models.BooleanField(default=False)),
                ('regalo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('es_jugador', models.BooleanField(default=True)),
                ('foto', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='perfil_usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('pt_1', models.IntegerField()),
                ('pt_2', models.IntegerField()),
                ('pt_3', models.IntegerField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Post')),
                ('cobrado', models.BooleanField(default=True)),
            ],
            bases=('main.post',),
        ),
        migrations.CreateModel(
            name='PostAlumno',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Post')),
            ],
            bases=('main.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='escrito_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='nota',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Paquete'),
        ),
        migrations.AddField(
            model_name='compra',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nota'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Equipo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Grado'),
        ),
        migrations.AddField(
            model_name='postalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Alumno'),
        ),
        migrations.AddField(
            model_name='postalumno',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PostCategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set([('alumno', 'reto')]),
        ),
    ]
