# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160901_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
