# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160818_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punteo',
            name='apuesta',
        ),
        migrations.RemoveField(
            model_name='punteo',
            name='nota',
        ),
        migrations.AddField(
            model_name='paquete',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reto',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='Punteo',
        ),
    ]
