# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alumno_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portada',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Portada de usuario', null=True, upload_to='portada_usuario', verbose_name='Portada de usuario'),
        ),
    ]
