# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de equipo', null=True, upload_to='images', verbose_name='Logo de equipo'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
