# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 16:23
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160902_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen de paquete', null=True, upload_to='imagen_paquete', verbose_name='Imagen de paquete'),
        ),
    ]
