# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160820_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de equipo', null=True, upload_to='main/images/equipo_logo', verbose_name='Logo de equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set([('alumno', 'reto')]),
        ),
    ]
