# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paquete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
    ]
