# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='imagen_mensaje'),
        ),
        migrations.AddField(
            model_name='postalumno',
            name='para',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
    ]
