# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170216_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalumno',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
