# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_postalumno_visto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.SlugField(max_length=25)),
                ('alias', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='payment_ref',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='main.Equipo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nota',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='main.Reto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.TipoTarjeta'),
        ),
    ]
