# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:29
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160831_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='portada',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Portada de equipo', null=True, upload_to='equipo_portada', verbose_name='Portada de equipo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='bg',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='materia_media'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='icon',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='materia_media'),
        ),
    ]
